// 挂载到 window 对象，确保在任何移动端浏览器中跨文件绝对可用
window.CONFIG = {
    GLOBAL_OVERLOAD_EFFICIENCY: 0.5,
    GLOBAL_WASTE_TO_HEAT_COEFF: 2.0,
    GLOBAL_OVERHEAT_DMG_COEFF: 0.5,
    DOPPLER_THRESHOLD: 100,
    TICK_RATE: 10,
    TICK_INTERVAL_MS: 100
};
